//
//  Datas.swift
//  FCRef
//
//  Created by Mathieu @theunknowman_80 on Twitter 27/05/2023.
//

import Foundation


class DatasL1 {
    
    static let get = DatasL1()
    
    //List of stadium for the ligue 1 clubs only, using the struct of "Stadium" and lat and long of each football stade.
    
    
    let ajacc = Stadium(name: "Stade François Coty", lat: 41.93117401108095, long: 8.777157315775337, capacity: 10492)
    let anger = Stadium(name: "Raymond-Kopa", lat: 47.46116389591454, long: -0.5307176067776599, capacity: 19800)
    let aux = Stadium(name: "l'Abbé-Deschamps", lat: 47.7868504519878, long: 3.5885803953515714, capacity: 18541)
    let bre = Stadium(name: "Francis-Le Blé", lat: 48.40381186341742, long: -4.462135419031356, capacity: 15051)
    let cle = Stadium(name: "Gabriel-Montpied", lat: 45.81593000143684, long: 3.121721012442966, capacity: 16000)
    let len = Stadium(name: "Bollaert-Delelis", lat: 50.432995050558965, long: 2.815051410835633, capacity: 37705)
    let li = Stadium(name: "Decathlon Arena - Pierre-Mauroy", lat: 50.612033018872346, long: 3.1305463126953628, capacity: 49082)
    let lor = Stadium(name: "Le Moustoir", lat: 47.74875210227741, long: -3.3693078266819385, capacity: 14640)
    let lyon = Stadium(name: "Groupama Stadium", lat: 45.76519815322528, long: 4.982140870111809, capacity: 59186)
    let marseille = Stadium(name: "Orange Vélodrome", lat: 43.269989676850116, long: 5.395869258566398, capacity: 67394)
    let monaco = Stadium(name: "Louis-II", lat: 43.72771485949294, long: 7.4156305707745815, capacity: 18523)
    let monp = Stadium(name: "La Mosson", lat: 43.62225987078509, long: 3.8120734258268714, capacity: 32900)
    let nante = Stadium(name: "La Beaujoire", lat: 47.25622688292394, long: -1.5247285369130321, capacity: 37473)
    let nice = Stadium(name: "Allianz Riviera", lat: 43.705197241411625, long: 7.192611602814414, capacity: 35624)
    let parisSg = Stadium(name: "Parc des Princes", lat: 48.84161371157487, long: 2.2521199473077256, capacity: 48583)
    let rei = Stadium(name: "Auguste-Delaune", lat: 49.24716709638506, long: 4.023898262350157, capacity: 21029)
    let ren = Stadium(name: "Roazhon Park", lat: 48.107584783636916, long: -1.712810335860264, capacity: 29194)
    let stras = Stadium(name: "La Meinau", lat: 48.55970088589111, long: 7.753583626077895, capacity: 26109)
    let toul = Stadium(name: "Stadium TFC", lat: 43.583361828051274, long: 1.433974566379179, capacity: 33150)
    let troy = Stadium(name: "Stade de l'Aube", lat: 48.3076461862281, long: 4.0984401670862445, capacity: 20420)
    
    //Adding informations about Football Clubs in L1 now with the stuct in file "ClubsLigue1" don't forget, the nickname was the same name of the logo in assets.
    
    var acj: FootballClubL1 {
        return FootballClubL1(name: "Athletic Club Ajaccien", nickname: "ajaccio", city: "Ajaccio", stadium: ajacc, desc: "L'AC Ajaccio, également connu sous le nom d'Ajaccio, est un club de football corse avec une longue histoire. Le club a connu plusieurs succès au fil des ans et a réussi à atteindre la Ligue 1 à plusieurs reprises. Bien qu'il n'ait pas le même rayonnement que certains grands clubs français, Ajaccio est apprécié pour son engagement et sa fierté régionale. Leurs matchs à domicile sont disputés au Stade François-Coty, situé à Ajaccio. L'AC Ajaccio est un club qui a un fort soutien de ses fans locaux et joue un rôle important dans le football corse.", championnatDeFrance: [], coupeDeFrance: [], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
        
    var angers: FootballClubL1 {
        return FootballClubL1(name: "Angers Sporting Club de l'Ouest",nickname: "angers", city: "Angers", stadium: anger, desc: "Angers SCO, souvent simplement appelé Angers, est un club de football français basé dans la ville d'Angers, dans l'ouest de la France. Le club a une histoire riche et a connu des succès remarquables au fil des ans. Après avoir navigué entre les divisions inférieures, Angers SCO est revenu en Ligue 1 en 2015 et a réussi à se maintenir dans l'élite depuis lors. Le club joue ses matchs à domicile au Stade Raymond-Kopa, un stade moderne d'une capacité d'environ 17 000 spectateurs. Angers SCO est apprécié pour son style de jeu dynamique et son esprit combatif, et il est soutenu par une base de fans passionnés dans la région d'Angers.", championnatDeFrance: [], coupeDeFrance: [], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
        
    var auxerre:FootballClubL1 {
       return FootballClubL1(name: "AJ Auxerre",nickname: "auxerre", city: "Auxerre", stadium: aux, desc: "L'AJ Auxerre est un club de football français basé dans la ville d'Auxerre, en Bourgogne. Le club a connu une période glorieuse dans les années 1990, sous la direction de l'entraîneur emblématique Guy Roux. Pendant cette période, Auxerre a remporté le championnat de France et a même atteint les demi-finales de la Ligue des champions. Le club est connu pour son centre de formation réputé, qui a produit de nombreux talents du football français. L'équipe joue ses matchs à domicile au Stade de l'Abbé-Deschamps, un stade historique qui peut accueillir environ 18 000 spectateurs. Auxerre est un club respecté en France et continue d'attirer l'attention grâce à son identité régionale et à son engagement envers le développement des jeunes joueurs.", championnatDeFrance: [1994,1996,2003,2005], coupeDeFrance: [1996], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var brest: FootballClubL1 {
        return FootballClubL1(name: "Stade Brestois 29",nickname: "brest", city: "Brest", stadium: bre, desc: "Le Stade Brestois 29, communément appelé Brest, est un club de football français basé dans la ville de Brest, en Bretagne. Le club a connu une ascension remarquable ces dernières années, passant des divisions inférieures à la Ligue 1. Depuis son retour dans l'élite en 2019, Brest s'est imposé comme une équipe compétitive et combative. Le club joue ses matchs à domicile au Stade Francis-Le Blé, un stade moderne d'une capacité d'environ 15 000 spectateurs. Les matchs à domicile de Brest sont réputés pour leur atmosphère animée, avec des supporters passionnés soutenant leur équipe. Brest est apprécié pour son style de jeu offensif et son esprit combatif, et il joue un rôle important dans le football breton.", championnatDeFrance: [], coupeDeFrance: [], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var clermont: FootballClubL1 {
        return FootballClubL1(name: "Clermont Foot 63",nickname: "clermont", city: "Clermont-Ferrand", stadium: cle, desc: "Clermont Foot 63, souvent simplement appelé Clermont, est un club de football français basé à Clermont-Ferrand, dans la région Auvergne-Rhône-Alpes. Le club a connu une progression constante au cours des dernières années, passant des divisions inférieures à l'élite du football français. En 2021, Clermont a accédé à la Ligue 1 pour la première fois de son histoire. Le club joue ses matchs à domicile au Stade Gabriel-Montpied, un stade d'une capacité d'environ 11 980 spectateurs. Clermont est reconnu pour son esprit d'équipe et son jeu dynamique, ce qui lui a permis de se démarquer lors de ses montées successives. L'arrivée de Clermont en Ligue 1 est un moment historique pour le club et représente une fierté pour ses supporters et la ville de Clermont-Ferrand.", championnatDeFrance: [], coupeDeFrance: [], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var lens: FootballClubL1 {
        return FootballClubL1(name: "Racing Club de Lens",nickname: "lens", city: "Lens", stadium: len, desc: "Le Racing Club de Lens, communément appelé Lens, est un club de football français basé dans la ville de Lens, dans les Hauts-de-France. Le club a une longue histoire et une grande base de supporters passionnés. Lens a connu des succès notables, notamment en remportant le championnat de France en 1998 et en participant à plusieurs compétitions européennes. Le club joue ses matchs à domicile au Stade Bollaert-Delelis, un stade emblématique d'une capacité d'environ 38 000 spectateurs. Les matchs de Lens sont réputés pour leur atmosphère électrique et l'engouement de leurs supporters, qui créent une ambiance unique. Lens est connu pour son jeu offensif et son esprit combatif, et est considéré comme l'un des clubs les plus appréciés en France.", championnatDeFrance: [1998], coupeDeFrance: [], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var ol : FootballClubL1 {
        return FootballClubL1(name: "Olympique Lyonnais",nickname: "lyon", city: "Lyon", stadium: lyon, desc: "L'Olympique Lyonnais, communément appelé Lyon, est l'un des clubs les plus titrés et les plus emblématiques du football français. Basé dans la ville de Lyon, le club a dominé la scène nationale pendant de nombreuses années, remportant de nombreux championnats de France consécutifs au début des années 2000. Lyon est également connu pour son succès en Coupe de France et en Coupe de la Ligue. L'équipe joue ses matchs à domicile au Groupama Stadium, un stade ultramoderne d'une capacité d'environ 59 000 spectateurs. Lyon est réputé pour son jeu offensif, sa formation de jeunes joueurs talentueux et son engagement envers le développement du football féminin, avec son équipe féminine ayant remporté plusieurs titres nationaux et européens. Lyon est un club qui suscite un grand engouement parmi ses supporters et reste une force majeure du football français.", championnatDeFrance: [2002, 2003, 2004, 2005, 2006, 2007, 2008], coupeDeFrance: [1964, 1967, 1973, 2008, 2012], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var lille: FootballClubL1 {
        return FootballClubL1(name: "L'OSC Lille",nickname: "lille", city: "Lille", stadium: li, desc: "Le Lille OSC, souvent simplement appelé Lille, est un club de football français basé dans la ville de Lille, dans les Hauts-de-France. Le club a connu une ascension notable ces dernières années, remportant le championnat de France de Ligue 1 lors de la saison 2020-2021. Lille est également connu pour sa formation de jeunes joueurs talentueux et sa capacité à rivaliser avec les grands clubs français malgré un budget relativement modeste. L'équipe joue ses matchs à domicile au Stade Pierre-Mauroy, un stade moderne d'une capacité d'environ 50 000 spectateurs. Lille est admiré pour son style de jeu dynamique, son travail d'équipe et sa capacité à produire des talents prometteurs. Le club bénéficie d'un soutien passionné de la part de ses supporters, qui créent une atmosphère vibrante lors des matchs à domicile.", championnatDeFrance: [1946, 1954, 2011, 2021], coupeDeFrance: [1946, 1947, 1948, 1953, 1955, 2011], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var lorient: FootballClubL1 {
        return FootballClubL1(name: "Football Club Lorient-Bretagne Sud",nickname: "lorient", city: "Lorient", stadium: lor, desc: "Le FC Lorient est un club de football français basé dans la ville de Lorient, en Bretagne. Fondé en 1926, le club a connu des hauts et des bas au cours de son histoire, mais est devenu un pilier de la Ligue 1 ces dernières années. Lorient est réputé pour son style de jeu offensif et attrayant, et est connu pour son engagement envers le développement des jeunes joueurs.Le club joue ses matchs à domicile au Stade du Moustoir, un stade d'une capacité d'environ 18 500 spectateurs. Les rencontres à domicile de Lorient sont animées par une foule passionnée, créant une atmosphère unique.Le FC Lorient a remporté la Coupe de France à deux reprises et a également obtenu des succès en deuxième division, avec plusieurs promotions en Ligue 1. Le club est fier de sa connexion avec sa région et bénéficie d'un soutien fidèle de la part de ses supporters.Avec sa philosophie de jeu attractive et son ambition constante, Lorient continue de se développer et de s'affirmer comme un club compétitif au sein de la Ligue 1.", championnatDeFrance: [], coupeDeFrance: [2002], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var om: FootballClubL1 {
        return FootballClubL1(name: "Olympique de Marseille",nickname: "marseille", city: "Marseille", stadium: marseille, desc: "L'Olympique de Marseille (OM) est l'un des clubs de football les plus emblématiques et prestigieux de France. Basé à Marseille, dans le sud de la France, le club a une longue histoire et une base de supporters passionnés, connus sous le nom de \("l'armée marseillaise"). Fondé en 1899, l'OM a remporté de nombreux titres, dont dix championnats de France et dix coupes de France. Le club est également connu pour ses performances remarquables en compétitions européennes, notamment avec une victoire en Ligue des champions en 1993. L'OM joue ses matchs à domicile au Stade Vélodrome, un stade légendaire d'une capacité de plus de 67 000 spectateurs. L'équipe de l'OM est réputée pour son jeu offensif, son engagement et sa passion sur le terrain. L'OM représente fièrement la ville de Marseille et incarne l'âme du football français.", championnatDeFrance: [1937, 1948, 1971, 1972, 1989, 1990, 1991, 1992, 2010], coupeDeFrance: [1924, 1926, 1927, 1935, 1938, 1943, 1969, 1972, 1976, 1989], championLeagueUEFA: [1993], europaLeagueUEFA: [])
    }
    
    var asm: FootballClubL1 {
        return FootballClubL1(name: "AS Monaco",nickname: "monaco", city: "Monaco", stadium: monaco, desc: "L'AS Monaco est un club de football français basé à Monaco, un petit État souverain situé sur la Côte d'Azur. Fondé en 1924, le club a connu des périodes de succès et est reconnu pour son jeu offensif et son recrutement de jeunes talents prometteurs. L'AS Monaco a remporté plusieurs titres de championnat de France, dont le plus récent en 2017. Le club est également apprécié pour ses performances en compétitions européennes, atteignant notamment la finale de la Ligue des champions en 2004. L'AS Monaco évolue au Stade Louis-II, un stade emblématique situé à Monaco, qui offre une vue magnifique sur la mer Méditerranée. Avec son histoire riche et son style de jeu attrayant, l'AS Monaco continue d'être une force compétitive en Ligue 1 et reste un club admiré dans le paysage du football français.", championnatDeFrance: [1961, 1963, 1978, 1982, 1988, 1997, 2000, 2017], coupeDeFrance: [1960, 1963, 1980, 1985, 1991], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var montpellier: FootballClubL1 {
        return FootballClubL1(name: "Montpellier-Herault Sport Club",nickname: "montpellier", city: "Montpellier", stadium: monp, desc: "Le Montpellier Hérault Sport Club, communément appelé Montpellier HSC, est un club de football français basé à Montpellier, dans le sud de la France. Fondé en 1919, le club a connu une ascension remarquable ces dernières années. Montpellier HSC a remporté son premier et unique titre de champion de France en 2012, créant une surprise mémorable dans le paysage du football français. Le club est réputé pour son esprit combatif et son style de jeu audacieux. Montpellier HSC joue ses matchs à domicile au Stade de la Mosson, un stade accueillant près de 32 900 spectateurs. Le club a su développer une identité forte et possède une base de supporters loyaux, qui le soutiennent avec passion. Montpellier HSC continue de se battre pour atteindre les plus hautes marches du football français et représente fièrement la ville de Montpellier dans le championnat de Ligue 1.", championnatDeFrance: [2012], coupeDeFrance: [1990], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var nantes: FootballClubL1 {
        return FootballClubL1(name: "FC Nantes",nickname: "nantes", city: "Nantes", stadium: nante, desc: "Le FC Nantes, également connu sous le nom de \("Les Canaris"), est un club de football français basé à Nantes, dans l'ouest de la France. Fondé en 1943, le FC Nantes est l'un des clubs les plus emblématiques du pays. Il a connu une période de succès dans les années 1970 et 1980, remportant huit titres de champion de France entre 1965 et 2001.Le club est connu pour son style de jeu offensif et créatif, ainsi que pour sa formation de jeunes joueurs. Le FC Nantes a une longue tradition de développer des talents et de les intégrer dans l'équipe première. Le stade du FC Nantes est le Stade de la Beaujoire - Louis Fonteneau, qui peut accueillir environ 38 000 spectateurs. C'est dans ce stade que le club joue ses matchs à domicile et crée une ambiance animée avec ses fidèles supporters.Malgré des périodes de transition, le FC Nantes reste un club respecté et suivi par les amateurs de football français. Il cherche à retrouver sa gloire passée et à rivaliser avec les meilleures équipes du championnat de Ligue 1. Le FC Nantes est un symbole du football dans la région de Nantes et continue d'inspirer les générations de fans de football.", championnatDeFrance: [1965, 1966, 1973, 1977, 1980, 1983, 1995, 2001], coupeDeFrance: [1979, 1999, 2000, 2022], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var ocg: FootballClubL1 {
        return FootballClubL1(name: "Olympique Gymnaste Club Nice Côte d'Azur",nickname: "nice", city: "Nice", stadium: nice, desc: "L'OGC Nice, également connu sous le nom de \("Les Aiglons"), est un club de football français basé à Nice, sur la Côte d'Azur. Fondé en 1904, le club possède une riche histoire et une base de supporters passionnés. Nice est réputé pour son style de jeu technique et attractif, mettant l'accent sur le développement de jeunes talents. Le club a remporté quatre titres de champion de France, le dernier en 1959. Le stade principal du club est l'Allianz Riviera, un stade moderne d'une capacité d'environ 36 000 spectateurs. Nice est une ville touristique dynamique et le club représente fièrement la région dans le championnat de Ligue 1. L'OGC Nice aspire à renouer avec le succès et à écrire de nouvelles pages dans son histoire, tout en offrant un spectacle de qualité à ses supporters loyaux.", championnatDeFrance: [1951, 1952, 1956, 1959], coupeDeFrance: [1952, 1954, 1997], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var psg: FootballClubL1 {
        return FootballClubL1(name: "Paris-Saint-Germain Football Club",nickname: "paris", city: "Paris", stadium: parisSg, desc: "Le Paris Saint-Germain, connu sous le nom de PSG, est le club de football le plus prestigieux en France, basé à Paris. Fondé en 1970, le PSG a connu une ascension fulgurante pour devenir l'une des équipes les plus puissantes d'Europe. Le club a remporté de nombreux titres nationaux, avec plus de dix titres de champion de France à son actif, notamment ceux des saisons 1985-1986, 1993-1994, 2012-2013, et une série impressionnante de sept titres consécutifs de 2013-2014 à 2019-2020. En plus de sa domination en Ligue 1, le PSG a également remporté un grand nombre de coupes nationales, dont de multiples Coupes de France et Coupes de la Ligue. Sur la scène européenne, le club a atteint la finale de la Ligue des champions de l'UEFA en 2020, et a participé régulièrement aux compétitions européennes. Le PSG a connu une période de croissance significative depuis son acquisition par le groupe Qatar Sports Investments en 2011. Cette nouvelle ère a permis au club de recruter des talents de classe mondiale, tels que Zlatan Ibrahimović, Thiago Silva, Neymar Jr et Kylian Mbappé. Ces joueurs d'exception ont aidé le PSG à renforcer sa position sur la scène européenne et à rivaliser avec les meilleurs clubs du continent.Le Parc des Princes, stade emblématique du PSG, est un lieu de rendez-vous pour les supporters passionnés du club. Avec une capacité d'environ 47 000 spectateurs, le stade offre une atmosphère enflammée lors des matchs à domicile", championnatDeFrance: [1986, 1994, 2013, 2014, 2015, 2016, 2018, 2019, 2020, 2022], coupeDeFrance: [1982, 1983, 1993, 1995, 1998, 2004, 2006, 2010, 2015, 2016, 2017, 2018, 2020, 2021], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var reims: FootballClubL1 {
        return FootballClubL1(name: "Stade de Reims",nickname: "reims", city: "Reims", stadium: rei, desc: "Le Stade de Reims, communément appelé Reims, est un club de football français basé à Reims, dans la région du Grand Est. Fondé en 1910, le club a une riche histoire et est considéré comme l'un des pionniers du football français. Reims a connu son apogée dans les années 1950, remportant six titres de champion de France consécutifs de 1949 à 1955.Le club est connu pour son style de jeu dynamique et offensif, ainsi que pour sa capacité à former et développer de jeunes talents. Reims a également réalisé des exploits mémorables en compétitions européennes, atteignant la finale de la Coupe d'Europe des clubs champions (ancêtre de la Ligue des champions) à deux reprises, en 1956 et 1959. Le stade du club est le Stade Auguste-Delaune, qui peut accueillir environ 21 000 spectateurs. Reims a une base de supporters passionnés qui continuent de soutenir l'équipe avec ferveur.Bien que Reims n'ait pas remporté de titre majeur depuis les années 1950, le club reste une figure importante du football français et cherche à retrouver sa gloire passée. Reims est un symbole de fierté pour la ville et continue de jouer un rôle clé dans le paysage du football français.", championnatDeFrance: [1949, 1953, 1955, 1958, 1960, 1962], coupeDeFrance: [1950, 1958], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
        
    var rennes: FootballClubL1 {
        return FootballClubL1(name: "Stade Rennais Football Club",nickname: "rennes", city: "Rennes", stadium: ren, desc: "Le Stade Rennais Football Club, plus communément appelé Rennes, est un club de football français basé à Rennes, en Bretagne. Fondé en 1901, le club a une longue histoire et est considéré comme l'un des clubs les plus anciens de France. Rennes a connu des hauts et des bas au fil des années, mais a réussi à se maintenir dans l'élite du football français.Le club est connu pour son identité régionale forte et son engagement envers le développement des jeunes joueurs. Rennes a également connu des succès en coupe nationale, remportant la Coupe de France à plusieurs reprises, dont les éditions 1965, 1971 et 2019. Ces victoires ont permis au club de représenter la France dans les compétitions européennes. Le Roazhon Park, également connu sous le nom de Stade de la Route de Lorient, est le stade emblématique du club, offrant une capacité d'environ 29 000 spectateurs. Les supporters de Rennes, connus sous le nom de \("Rouge et Noir"), sont réputés pour leur ferveur et leur soutien indéfectible. Rennes continue de se battre pour atteindre les sommets du football français et aspire à obtenir des succès réguliers en championnat et en compétitions nationales. Le club est un symbole de fierté pour la ville de Rennes et représente avec passion la Bretagne sur la scène footballistique française.", championnatDeFrance: [], coupeDeFrance: [1965, 1971, 2019], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var strasbourg: FootballClubL1 {
        return FootballClubL1(name: "Racing Club de Strasbourg Alsace",nickname: "strasbourg", city: "Strasbourg", stadium: stras, desc: "Le Racing Club de Strasbourg, communément appelé Strasbourg, est un club de football français basé à Strasbourg, en Alsace. Fondé en 1906, le club possède une longue histoire et une base de supporters dévoués. Strasbourg a connu des périodes de succès, notamment dans les années 1970 et 1980, remportant plusieurs titres de champion de France. Le club est connu pour son esprit combatif et son identité alsacienne forte. Strasbourg a également remporté la Coupe de la Ligue à plusieurs reprises, dont les éditions 1997, 2005 et 2019. Ces victoires ont permis au club de représenter la France dans les compétitions européennes. Le stade du club est le Stade de la Meinau, qui peut accueillir environ 26 000 spectateurs. C'est un lieu emblématique où les supporters strasbourgeois se rassemblent pour soutenir leur équipe. Bien que Strasbourg ait connu des périodes de relégation en divisions inférieures, le club a toujours réussi à rebondir et à retrouver sa place en Ligue 1. Strasbourg est un symbole de fierté pour la ville et la région alsacienne, et les supporters continuent d'encourager l'équipe avec passion et détermination. Le club aspire à retrouver les sommets du football français et à écrire de nouvelles pages glorieuses dans son histoire.", championnatDeFrance: [], coupeDeFrance: [1951, 1966, 2001], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var toulouse: FootballClubL1 {
        return FootballClubL1(name: "Toulouse Football Club",nickname: "toulouse", city: "Toulouse", stadium: toul, desc: "Le Toulouse Football Club, fondé en 1937, est un club de football français basé à Toulouse, en Occitanie. Tout au long de son histoire, le club a connu des hauts et des bas, mais a su se maintenir comme une institution importante dans le paysage du football français. Toulouse a connu des moments de gloire, notamment lors des années 2000, où le club a participé à plusieurs compétitions européennes. En 1957, le TFC a remporté la Coupe de France, marquant ainsi un moment historique dans l'histoire du club. Après avoir été relégué en Ligue 2 en 2019, le Toulouse FC a montré sa détermination en remportant la première place du championnat de Ligue 2 lors de la saison 2021-2022. Cette victoire a marqué le retour tant attendu du club en Ligue 1, ravivant l'enthousiasme des supporters et renforçant les ambitions du club. Le Toulouse FC s'appuie sur son histoire et sa fierté régionale pour poursuivre son développement. Les supporters du club, passionnés et fidèles, continuent de soutenir l'équipe avec ferveur dans l'espoir de voir le TFC retrouver sa place parmi les meilleurs clubs français. L'histoire du Toulouse FC est marquée par des moments mémorables et des défis surmontés. Avec son retour en Ligue 1, le club s'efforcera de bâtir un avenir solide, en s'appuyant sur ses forces, son identité régionale et la passion de ses supporters pour continuer à écrire de nouveaux chapitres passionnants dans son histoire.", championnatDeFrance: [], coupeDeFrance: [2023], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    var troye: FootballClubL1 {
        return FootballClubL1(name: "Espérance Sportive Troyes Aube Champagne",nickname: "troyes", city: "Troyes", stadium: troy, desc: "L'ES Troyes AC, communément appelé Troyes, est un club de football français basé à Troyes, dans la région du Grand Est. Fondé en 1986, le club a connu plusieurs périodes de succès et de promotions entre les divisions du football français.Troyes a réalisé des exploits remarquables, notamment en atteignant la finale de la Coupe de France en 2001 et en remportant le championnat de Ligue 2 à plusieurs reprises, permettant ainsi au club de retrouver l'élite du football français.Le stade du club est le Stade de l'Aube, qui peut accueillir environ 20 000 spectateurs. Les supporters de Troyes, connus sous le nom de \("Les Irréductibles"), sont réputés pour leur ferveur et leur soutien indéfectible lors des matchs à domicile. Malgré certaines saisons en Ligue 1, Troyes a également connu des relégations et des périodes de reconstruction. Le club s'efforce de maintenir une stabilité sportive et aspire à atteindre une place solide dans le football français.Troyes est un symbole de fierté pour la ville et continue de représenter avec passion la région du Grand Est sur la scène du football national. Les supporters restent fidèles à leur équipe, en espérant voir le club gravir les échelons et retrouver une place durable en Ligue 1.", championnatDeFrance: [], coupeDeFrance: [], championLeagueUEFA: [], europaLeagueUEFA: [])
    }
    
    //We create two variables to store the Arrays of the Stadium and Club tables for later use in our various functions
    
    var allStadiums: [Stadium] {
        return [ajacc, aux, anger, cle, parisSg, lyon, marseille, li, len, lor, monaco, nante, monp, ren, stras, troy, bre, rei, toul, nice]
    }
    
    var allClubsL1: [FootballClubL1] {
        return [auxerre, angers, clermont, psg, ol, om, lille, lens, lorient, asm, nantes, montpellier, rennes, strasbourg, troye, brest, reims, toulouse, ocg, acj]
    }
    
    }
